<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210424163347 extends AbstractMigration
{
    public function isTransactional(): bool
    {
        return true;
    }

    public function getDescription() : string
    {
        return 'Initial migration';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE airfields (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, tcn VARCHAR(8) DEFAULT NULL, ils VARCHAR(16) DEFAULT NULL, latitude VARCHAR(32) DEFAULT NULL, longitude VARCHAR(32) DEFAULT NULL, elevation_feet VARCHAR(10) DEFAULT NULL, elevation_meters VARCHAR(10) DEFAULT NULL, atc VARCHAR(64) DEFAULT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alerts (id INT AUTO_INCREMENT NOT NULL, target_user_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, class VARCHAR(255) DEFAULT \'fa-info-circle\' NOT NULL, color VARCHAR(255) DEFAULT \'text-primary\' NOT NULL, url VARCHAR(255) DEFAULT \'#\', message LONGTEXT NOT NULL, seen TINYINT(1) NOT NULL, deleted TINYINT(1) NOT NULL, create_time DATETIME NOT NULL, INDEX IDX_F77AC06B6C066AFE (target_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_categories (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, titleEn VARCHAR(255) NOT NULL, active TINYINT(1) DEFAULT \'1\' NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_comments (id INT AUTO_INCREMENT NOT NULL, article_id INT DEFAULT NULL, author VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, comment LONGTEXT NOT NULL, likes INT DEFAULT 0 NOT NULL, dislikes INT DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_A7662417294869C (article_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_tags (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE articles (id INT AUTO_INCREMENT NOT NULL, server_id INT DEFAULT NULL, category_id INT DEFAULT NULL, tag_id INT DEFAULT NULL, title VARCHAR(128) NOT NULL, youtube_shortcode VARCHAR(255) DEFAULT NULL, title_en VARCHAR(128) NOT NULL, description VARCHAR(256) NOT NULL, description_en VARCHAR(256) NOT NULL, ru LONGTEXT NOT NULL, en LONGTEXT NOT NULL, public TINYINT(1) NOT NULL, isVideoPost TINYINT(1) DEFAULT NULL, meta_title VARCHAR(128) NOT NULL, meta_h1 VARCHAR(128) NOT NULL, meta_keyword VARCHAR(256) NOT NULL, meta_description LONGTEXT NOT NULL, meta_title_en VARCHAR(128) NOT NULL, meta_h1_en VARCHAR(128) NOT NULL, meta_keyword_en VARCHAR(256) NOT NULL, meta_description_en LONGTEXT NOT NULL, image VARCHAR(256) NOT NULL, views INT DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_BFDD31681844E6B7 (server_id), INDEX IDX_BFDD316812469DE2 (category_id), INDEX IDX_BFDD3168BAD26311 (tag_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE banlist (id INT AUTO_INCREMENT NOT NULL, server_id INT DEFAULT NULL, pilot_id INT DEFAULT NULL, ip_address VARCHAR(255) NOT NULL, reason VARCHAR(255) DEFAULT NULL, banned_from DATETIME NOT NULL, banned_until DATETIME NOT NULL, INDEX IDX_163B0651844E6B7 (server_id), INDEX IDX_163B065CE55439B (pilot_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE best_streaks (id INT AUTO_INCREMENT NOT NULL, pilot_id INT DEFAULT NULL, server_id INT DEFAULT NULL, streak_type VARCHAR(32) NOT NULL, streak INT NOT NULL, INDEX IDX_66C141A8CE55439B (pilot_id), INDEX IDX_66C141A81844E6B7 (server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE chat_messages (id INT AUTO_INCREMENT NOT NULL, sender_id INT NOT NULL, server_id INT DEFAULT NULL, message LONGTEXT NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_EF20C9A6F624B39D (sender_id), INDEX IDX_EF20C9A61844E6B7 (server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commands_queue (id INT AUTO_INCREMENT NOT NULL, command_name VARCHAR(255) NOT NULL, identifier_value BIGINT NOT NULL, executed TINYINT(1) DEFAULT \'0\' NOT NULL, failed TINYINT(1) DEFAULT \'0\' NOT NULL, execute_start_time DATETIME DEFAULT NULL, execute_end_time DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE current_kills (id INT AUTO_INCREMENT NOT NULL, server_id INT DEFAULT NULL, mission_registry_id INT DEFAULT NULL, tour_id INT DEFAULT NULL, unit_id INT DEFAULT NULL, pilot_id INT DEFAULT NULL, plane_id INT DEFAULT NULL, victim_id INT DEFAULT NULL, victim_plane_id INT DEFAULT NULL, action VARCHAR(32) DEFAULT \'destroyed\' NOT NULL, kill_time DATETIME NOT NULL, side VARCHAR(255) DEFAULT \'RED\' NOT NULL, points INT NOT NULL, victim_side VARCHAR(255) NOT NULL, is_human TINYINT(1) DEFAULT \'0\' NOT NULL, friendly_fire TINYINT(1) DEFAULT \'0\' NOT NULL, is_ai TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_8B7948A51844E6B7 (server_id), INDEX IDX_8B7948A52B284D0C (mission_registry_id), INDEX IDX_8B7948A515ED8D43 (tour_id), INDEX IDX_8B7948A5F8BD700D (unit_id), INDEX IDX_8B7948A5CE55439B (pilot_id), INDEX IDX_8B7948A5F53666A8 (plane_id), INDEX IDX_8B7948A544972A0E (victim_id), INDEX IDX_8B7948A577F461D0 (victim_plane_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE custom_page (id INT AUTO_INCREMENT NOT NULL, url VARCHAR(255) NOT NULL, title_en VARCHAR(255) NOT NULL, title_ru VARCHAR(255) NOT NULL, content_en LONGTEXT DEFAULT NULL, content_ru LONGTEXT DEFAULT NULL, is_public TINYINT(1) DEFAULT \'0\' NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE custom_tour_requests (id INT AUTO_INCREMENT NOT NULL, start DATETIME NOT NULL, started TINYINT(1) NOT NULL, title VARCHAR(255) NOT NULL, title_en VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dogfights (id INT AUTO_INCREMENT NOT NULL, pilot_id INT DEFAULT NULL, server_id INT DEFAULT NULL, mission_registry_id INT DEFAULT NULL, tour_id INT DEFAULT NULL, pilot_plane_id INT DEFAULT NULL, victim_id INT DEFAULT NULL, victim_plane_id INT DEFAULT NULL, ai_id INT DEFAULT NULL, pilot_side VARCHAR(255) NOT NULL, victim_side VARCHAR(255) NOT NULL, is_pvp TINYINT(1) DEFAULT \'0\' NOT NULL, in_air TINYINT(1) DEFAULT \'1\' NOT NULL, kill_time DATETIME NOT NULL, friendly TINYINT(1) NOT NULL, elo_calculated TINYINT(1) DEFAULT \'0\' NOT NULL, points INT NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_88B93457CE55439B (pilot_id), INDEX IDX_88B934571844E6B7 (server_id), INDEX IDX_88B934572B284D0C (mission_registry_id), INDEX IDX_88B9345715ED8D43 (tour_id), INDEX IDX_88B934579E9B4BC7 (pilot_plane_id), INDEX IDX_88B9345744972A0E (victim_id), INDEX IDX_88B9345777F461D0 (victim_plane_id), INDEX IDX_88B93457BD5E0D4B (ai_id), INDEX pilots_ranking_wins_idx (friendly, in_air, ai_id, victim_id, tour_id, server_id), INDEX pilots_ranking_dogfights_idx (friendly, in_air, victim_id, tour_id, server_id), INDEX pilots_ranking_loses_idx (friendly, victim_id, tour_id, server_id), INDEX missions_sessions_list (server_id, tour_id, pilot_side), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE elos (id INT AUTO_INCREMENT NOT NULL, pilot_id INT NOT NULL, tour_id INT DEFAULT NULL, server_id INT NOT NULL, plane_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, side VARCHAR(255) DEFAULT NULL, rating DOUBLE PRECISION DEFAULT \'1000\' NOT NULL, coefficient DOUBLE PRECISION DEFAULT \'40\' NOT NULL, INDEX IDX_4718BD87CE55439B (pilot_id), INDEX IDX_4718BD8715ED8D43 (tour_id), INDEX IDX_4718BD871844E6B7 (server_id), INDEX IDX_4718BD87F53666A8 (plane_id), INDEX pilots_elo_ranking_idx (side, type, tour_id, server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events (id INT AUTO_INCREMENT NOT NULL, pilot_id INT DEFAULT NULL, server_id INT DEFAULT NULL, mission_registry_id INT DEFAULT NULL, tour_id INT DEFAULT NULL, plane_id INT DEFAULT NULL, event VARCHAR(255) NOT NULL, side VARCHAR(255) NOT NULL, event_time DATETIME NOT NULL, INDEX IDX_5387574ACE55439B (pilot_id), INDEX IDX_5387574A1844E6B7 (server_id), INDEX IDX_5387574A2B284D0C (mission_registry_id), INDEX IDX_5387574A15ED8D43 (tour_id), INDEX IDX_5387574AF53666A8 (plane_id), INDEX pilots_events_ranking_idx (event, tour_id, server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faqs (id INT AUTO_INCREMENT NOT NULL, server_id INT DEFAULT NULL, question VARCHAR(255) NOT NULL, questionEn VARCHAR(255) NOT NULL, answer LONGTEXT NOT NULL, answerEn LONGTEXT NOT NULL, for_sender TINYINT(1) DEFAULT \'1\' NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_8934BEE51844E6B7 (server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE favor_planes (id INT AUTO_INCREMENT NOT NULL, pilot_id INT DEFAULT NULL, server_id INT DEFAULT NULL, plane_id INT DEFAULT NULL, INDEX IDX_2930ACC3CE55439B (pilot_id), INDEX IDX_2930ACC31844E6B7 (server_id), INDEX IDX_2930ACC3F53666A8 (plane_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE featured_videos (id INT AUTO_INCREMENT NOT NULL, server_id INT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, code VARCHAR(64) NOT NULL, order_number INT NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_392957931844E6B7 (server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE feedbacks (id INT AUTO_INCREMENT NOT NULL, firstname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, seen TINYINT(1) NOT NULL, deleted TINYINT(1) NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE flights (id INT AUTO_INCREMENT NOT NULL, server_id INT NOT NULL, theatre_id INT DEFAULT NULL, mission_registry_id INT NOT NULL, pilot_id INT NOT NULL, plane_id INT NOT NULL, tour_id INT NOT NULL, airfield_id INT DEFAULT NULL, side VARCHAR(255) DEFAULT \'RED\' NOT NULL, started TINYINT(1) DEFAULT \'0\' NOT NULL, start_flight_time DATETIME DEFAULT NULL, combat_flight TINYINT(1) DEFAULT \'0\' NOT NULL, night_flight TINYINT(1) DEFAULT \'0\' NOT NULL, bad_weather_flight TINYINT(1) DEFAULT \'0\' NOT NULL, group_flight TINYINT(1) DEFAULT \'0\' NOT NULL, emergency_flight TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_FC74B5EA1844E6B7 (server_id), INDEX IDX_FC74B5EAC80060CD (theatre_id), INDEX IDX_FC74B5EA2B284D0C (mission_registry_id), UNIQUE INDEX UNIQ_FC74B5EACE55439B (pilot_id), INDEX IDX_FC74B5EAF53666A8 (plane_id), INDEX IDX_FC74B5EA15ED8D43 (tour_id), INDEX IDX_FC74B5EA286FE424 (airfield_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE game_devices (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE instances (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, serial_number VARCHAR(255) NOT NULL, enabled TINYINT(1) DEFAULT \'0\' NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE json_messages (id INT AUTO_INCREMENT NOT NULL, server_id INT DEFAULT NULL, content LONGTEXT NOT NULL, deprecated TINYINT(1) DEFAULT \'0\' NOT NULL, executed TINYINT(1) DEFAULT \'0\' NOT NULL, success TINYINT(1) DEFAULT \'0\' NOT NULL, execute_time NUMERIC(10, 6) DEFAULT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_77C5B09B1844E6B7 (server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kills (id INT AUTO_INCREMENT NOT NULL, pilot_id INT DEFAULT NULL, server_id INT DEFAULT NULL, mission_registry_id INT DEFAULT NULL, tour_id INT DEFAULT NULL, plane_id INT DEFAULT NULL, unit_id INT DEFAULT NULL, side VARCHAR(255) NOT NULL, target_side VARCHAR(255) NOT NULL, kill_time DATETIME NOT NULL, friendly TINYINT(1) DEFAULT \'0\' NOT NULL, ground_kill TINYINT(1) DEFAULT \'0\', sea_kill TINYINT(1) DEFAULT \'0\', points INT NOT NULL, INDEX IDX_2F673FA1CE55439B (pilot_id), INDEX IDX_2F673FA11844E6B7 (server_id), INDEX IDX_2F673FA12B284D0C (mission_registry_id), INDEX IDX_2F673FA115ED8D43 (tour_id), INDEX IDX_2F673FA1F53666A8 (plane_id), INDEX IDX_2F673FA1F8BD700D (unit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE levels (id INT AUTO_INCREMENT NOT NULL, level INT NOT NULL, points BIGINT NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE logs (id INT AUTO_INCREMENT NOT NULL, tour_id INT DEFAULT NULL, server_id INT DEFAULT NULL, event VARCHAR(255) NOT NULL, theatre VARCHAR(255) DEFAULT NULL, event_time DATETIME NOT NULL, simulation_time DATETIME DEFAULT NULL, chat_message VARCHAR(255) DEFAULT NULL, initiator_nickname VARCHAR(255) DEFAULT NULL, initiator_email VARCHAR(255) DEFAULT NULL, initiator_side VARCHAR(255) DEFAULT NULL, initiator_ip_address VARCHAR(255) DEFAULT NULL, initiator_ucid VARCHAR(255) DEFAULT NULL, initiator_type VARCHAR(255) DEFAULT NULL, initiator_category VARCHAR(255) DEFAULT NULL, score INT DEFAULT NULL, target_nickname VARCHAR(255) DEFAULT NULL, target_side VARCHAR(255) DEFAULT NULL, target_ip VARCHAR(255) DEFAULT NULL, target_ucid VARCHAR(255) DEFAULT NULL, target_type VARCHAR(255) DEFAULT NULL, target_category VARCHAR(255) DEFAULT NULL, target_is_ground TINYINT(1) DEFAULT NULL, target_is_human TINYINT(1) DEFAULT NULL, messages_stack LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', weather LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', banlist LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', field LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', description LONGTEXT DEFAULT NULL, won VARCHAR(5) DEFAULT NULL, success TINYINT(1) DEFAULT \'0\' NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_F08FC65C15ED8D43 (tour_id), INDEX IDX_F08FC65C1844E6B7 (server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manuals (id INT AUTO_INCREMENT NOT NULL, plane_id INT DEFAULT NULL, image VARCHAR(256) DEFAULT NULL, document VARCHAR(255) NOT NULL, title VARCHAR(128) NOT NULL, title_en VARCHAR(128) NOT NULL, description LONGTEXT DEFAULT NULL, description_en LONGTEXT DEFAULT NULL, public TINYINT(1) DEFAULT \'1\' NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_8717121CF53666A8 (plane_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE map_units (id INT AUTO_INCREMENT NOT NULL, server_id INT DEFAULT NULL, identifier INT NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, is_human TINYINT(1) NOT NULL, is_static TINYINT(1) NOT NULL, country VARCHAR(255) NOT NULL, side VARCHAR(255) NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, altitude INT NOT NULL, heading INT NOT NULL, INDEX IDX_69463B251844E6B7 (server_id), UNIQUE INDEX unique_identifier_server_id (identifier, server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mission_registries (id INT AUTO_INCREMENT NOT NULL, theatre_id INT DEFAULT NULL, server_id INT DEFAULT NULL, tour_id INT DEFAULT NULL, mission_id INT DEFAULT NULL, start_time DATETIME NOT NULL, end_time DATETIME DEFAULT NULL, winner VARCHAR(255) DEFAULT NULL, finished TINYINT(1) DEFAULT \'0\', atmosphere_type INT DEFAULT NULL, groundTurbulence INT DEFAULT NULL, fog TINYINT(1) DEFAULT \'0\' NOT NULL, wind_speed_at_8000 INT DEFAULT NULL, wind_direction_at_8000 INT DEFAULT NULL, wind_speed_at_2000 INT DEFAULT NULL, wind_direction_at_2000 INT DEFAULT NULL, wind_speed_at_ground INT DEFAULT NULL, wind_direction_at_ground INT DEFAULT NULL, temperature INT DEFAULT NULL, weather_type INT DEFAULT NULL, qnh INT DEFAULT NULL, weather_name VARCHAR(255) DEFAULT NULL, fog_thickness INT DEFAULT NULL, fog_visibility INT DEFAULT NULL, visibility_distance INT DEFAULT NULL, dust_density INT DEFAULT NULL, dust TINYINT(1) DEFAULT \'0\' NOT NULL, clouds_thickness INT DEFAULT NULL, clouds_density INT DEFAULT NULL, clouds_base INT DEFAULT NULL, clouds_ip_recptns INT DEFAULT NULL, INDEX IDX_57906A8BC80060CD (theatre_id), INDEX IDX_57906A8B1844E6B7 (server_id), INDEX IDX_57906A8B15ED8D43 (tour_id), INDEX IDX_57906A8BBE6CAE90 (mission_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE missions (id INT AUTO_INCREMENT NOT NULL, server_id INT DEFAULT NULL, theatre_id INT DEFAULT NULL, name VARCHAR(128) NOT NULL, description LONGTEXT DEFAULT NULL, description_en LONGTEXT DEFAULT NULL, general_task LONGTEXT DEFAULT NULL, red_task LONGTEXT DEFAULT NULL, blue_task LONGTEXT DEFAULT NULL, neutral_task LONGTEXT DEFAULT NULL, is_event TINYINT(1) DEFAULT NULL, INDEX IDX_34F1D47E1844E6B7 (server_id), INDEX IDX_34F1D47EC80060CD (theatre_id), INDEX idx_name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mobile_device (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, android_identifier VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, notice_device TINYINT(1) NOT NULL, last_time DATETIME NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE online (id INT AUTO_INCREMENT NOT NULL, server_id INT DEFAULT NULL, pilot_id INT DEFAULT NULL, plane_id INT DEFAULT NULL, side VARCHAR(255) NOT NULL, enter_time DATETIME NOT NULL, frequencies LONGTEXT DEFAULT NULL, coordinates LONGTEXT DEFAULT NULL, INDEX IDX_9E32BEEA1844E6B7 (server_id), UNIQUE INDEX UNIQ_9E32BEEACE55439B (pilot_id), INDEX IDX_9E32BEEAF53666A8 (plane_id), INDEX idx_server_pilot (server_id, pilot_id), UNIQUE INDEX unique_pilot_and_server (pilot_id, server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partners (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, image VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pilots (id INT AUTO_INCREMENT NOT NULL, favourite_plane_id INT DEFAULT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, ip_address VARCHAR(255) DEFAULT NULL, youtube_channel_url VARCHAR(255) DEFAULT NULL, twitch_channel_url VARCHAR(255) DEFAULT NULL, checked TINYINT(1) DEFAULT \'0\' NOT NULL, ucid VARCHAR(255) NOT NULL, online TINYINT(1) DEFAULT \'0\', views INT DEFAULT 0 NOT NULL, hardware LONGTEXT DEFAULT NULL, about LONGTEXT DEFAULT NULL, birthday DATE DEFAULT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, country VARCHAR(64) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, facebook_id VARCHAR(255) DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, surname VARCHAR(255) DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', enabled TINYINT(1) NOT NULL, phone VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_9EE6E18CE7927C74 (email), INDEX IDX_9EE6E18CA5FBE00B (favourite_plane_id), INDEX idx_ucid (ucid), INDEX idx_username (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pilot_game_devices (pilot_id INT NOT NULL, game_device_id INT NOT NULL, INDEX IDX_16DC7927CE55439B (pilot_id), INDEX IDX_16DC7927460206D6 (game_device_id), PRIMARY KEY(pilot_id, game_device_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE planes (id INT AUTO_INCREMENT NOT NULL, weather_limit_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, red_image VARCHAR(255) DEFAULT NULL, blue_image VARCHAR(255) DEFAULT NULL, is_mod TINYINT(1) DEFAULT \'1\' NOT NULL, is_helicopter TINYINT(1) DEFAULT \'0\' NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, UNIQUE INDEX UNIQ_F677FF065E237E06 (name), INDEX IDX_F677FF0640F7E601 (weather_limit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, UNIQUE INDEX UNIQ_9BACE7E1C74F2195 (refresh_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE registration_tickets (id INT AUTO_INCREMENT NOT NULL, pilot_id INT DEFAULT NULL, email VARCHAR(255) NOT NULL, token VARCHAR(64) NOT NULL, deadline DATETIME NOT NULL, accepted TINYINT(1) DEFAULT \'0\' NOT NULL, issued TINYINT(1) DEFAULT \'0\' NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, UNIQUE INDEX UNIQ_1437C852CE55439B (pilot_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rewards (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, title_en VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, description_en VARCHAR(255) NOT NULL, image VARCHAR(255) NOT NULL, func VARCHAR(255) NOT NULL, lifetime_reward TINYINT(1) DEFAULT \'0\' NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sender_config (id INT AUTO_INCREMENT NOT NULL, server_id INT NOT NULL, active TINYINT(1) NOT NULL, greenie_board TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_2A4111631844E6B7 (server_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sender_updates (id INT AUTO_INCREMENT NOT NULL, notes LONGTEXT DEFAULT NULL, exe VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE servers (id INT AUTO_INCREMENT NOT NULL, mission_id INT DEFAULT NULL, instance_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, identifier VARCHAR(64) NOT NULL, version VARCHAR(64) DEFAULT NULL, order_position INT DEFAULT 100000 NOT NULL, image VARCHAR(255) DEFAULT NULL, discord_server_id VARCHAR(255) DEFAULT NULL, discord_bot_token VARCHAR(255) DEFAULT NULL, send_discord_notifications TINYINT(1) DEFAULT \'0\' NOT NULL, send_discord_server_notifications TINYINT(1) DEFAULT \'0\' NOT NULL, send_discord_flight_notifications TINYINT(1) DEFAULT \'0\' NOT NULL, send_discord_friendly_fire_notifications TINYINT(1) DEFAULT \'0\' NOT NULL, send_discord_combat_notifications TINYINT(1) DEFAULT \'0\' NOT NULL, discord_webhook VARCHAR(255) DEFAULT NULL, background_image VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, description_en LONGTEXT DEFAULT NULL, address VARCHAR(255) DEFAULT \'0.0.0.0\' NOT NULL, port VARCHAR(255) DEFAULT \'10308\', folder VARCHAR(255) DEFAULT NULL, ts3_address VARCHAR(255) DEFAULT NULL, srs_address VARCHAR(255) DEFAULT NULL, discord_address VARCHAR(255) DEFAULT NULL, mumble_address VARCHAR(255) DEFAULT NULL, srs_file VARCHAR(255) DEFAULT NULL, reports_location VARCHAR(255) DEFAULT \'C:\\\\\' NOT NULL, active TINYINT(1) DEFAULT \'0\' NOT NULL, has_sender TINYINT(1) DEFAULT \'1\' NOT NULL, is_online TINYINT(1) DEFAULT \'0\' NOT NULL, show_map TINYINT(1) DEFAULT \'0\' NOT NULL, show_banlist TINYINT(1) DEFAULT \'0\' NOT NULL, start_time DATETIME DEFAULT NULL, last_activity DATETIME DEFAULT NULL, is_aerobatics TINYINT(1) NOT NULL, is_pvp TINYINT(1) NOT NULL, is_modern TINYINT(1) NOT NULL, is_beta TINYINT(1) NOT NULL, send_version_update_emails TINYINT(1) NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_4F8AF5F7BE6CAE90 (mission_id), INDEX IDX_4F8AF5F73A51721D (instance_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE server_admins (server_id INT NOT NULL, admin_id INT NOT NULL, INDEX IDX_DB9C2CC91844E6B7 (server_id), INDEX IDX_DB9C2CC9642B8210 (admin_id), PRIMARY KEY(server_id, admin_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE settings (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, keyword VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, default_value VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_E545A0C55A93713B (keyword), INDEX keyword_idx (keyword), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE slides (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, title_en VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, description_en VARCHAR(255) NOT NULL, image VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, url_title VARCHAR(255) DEFAULT NULL, url_title_en VARCHAR(255) DEFAULT NULL, order_number INT NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE social_links (id INT AUTO_INCREMENT NOT NULL, icon VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, new_window TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sorties (id INT AUTO_INCREMENT NOT NULL, pilot_id INT DEFAULT NULL, server_id INT DEFAULT NULL, theatre_id INT DEFAULT NULL, mission_registry_id INT DEFAULT NULL, tour_id INT DEFAULT NULL, plane_id INT NOT NULL, takeoff_airfield_id INT DEFAULT NULL, landing_airfield_id INT DEFAULT NULL, side VARCHAR(255) NOT NULL, start_flight DATETIME NOT NULL, end_flight DATETIME NOT NULL, total_time INT NOT NULL, status VARCHAR(255) DEFAULT NULL, night_flight TINYINT(1) DEFAULT \'0\' NOT NULL, combat_flight TINYINT(1) DEFAULT \'0\' NOT NULL, bad_weather_flight TINYINT(1) DEFAULT \'0\' NOT NULL, group_flight TINYINT(1) DEFAULT \'0\' NOT NULL, emergency_flight TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_488163E8CE55439B (pilot_id), INDEX IDX_488163E81844E6B7 (server_id), INDEX IDX_488163E8C80060CD (theatre_id), INDEX IDX_488163E82B284D0C (mission_registry_id), INDEX IDX_488163E815ED8D43 (tour_id), INDEX IDX_488163E8F53666A8 (plane_id), INDEX IDX_488163E87F8DF58 (takeoff_airfield_id), INDEX IDX_488163E88BE8978B (landing_airfield_id), INDEX pilots_sorties_ranking_idx (landing_airfield_id, tour_id, server_id), INDEX pilots_ranking_sorties_idx (total_time), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE streaks (id INT AUTO_INCREMENT NOT NULL, pilot_id INT DEFAULT NULL, server_id INT DEFAULT NULL, tour_id INT DEFAULT NULL, is_air TINYINT(1) DEFAULT \'0\' NOT NULL, is_current TINYINT(1) DEFAULT \'0\' NOT NULL, streak INT DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, INDEX IDX_59A5DD7CCE55439B (pilot_id), INDEX IDX_59A5DD7C1844E6B7 (server_id), INDEX IDX_59A5DD7C15ED8D43 (tour_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE theatres (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, night_start TIME DEFAULT NULL, night_end TIME DEFAULT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tours (id INT AUTO_INCREMENT NOT NULL, start_time DATETIME NOT NULL, end_time DATETIME DEFAULT NULL, title VARCHAR(255) NOT NULL, title_en VARCHAR(255) NOT NULL, finished TINYINT(1) DEFAULT \'0\' NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE unit_types (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(64) NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, UNIQUE INDEX UNIQ_D202F73B2B36786B (title), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE units (id INT AUTO_INCREMENT NOT NULL, unit_type_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, air_unit TINYINT(1) DEFAULT \'0\', ground_unit TINYINT(1) DEFAULT \'0\', sea_unit TINYINT(1) DEFAULT \'0\', UNIQUE INDEX UNIQ_E9B074495E237E06 (name), INDEX IDX_E9B0744991058251 (unit_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE visitors (id INT AUTO_INCREMENT NOT NULL, server_id INT DEFAULT NULL, mission_registry_id INT DEFAULT NULL, tour_id INT DEFAULT NULL, pilot_id INT DEFAULT NULL, enter_time DATETIME NOT NULL, INDEX IDX_7B74A43F1844E6B7 (server_id), INDEX IDX_7B74A43F2B284D0C (mission_registry_id), INDEX IDX_7B74A43F15ED8D43 (tour_id), INDEX IDX_7B74A43FCE55439B (pilot_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE weather_limits (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, clouds_base_day INT NOT NULL, clouds_base_night INT NOT NULL, visibility_day INT NOT NULL, visibility_night INT NOT NULL, created_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, updated_at DATETIME DEFAULT \'2000-01-01 00:00:00\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE alerts ADD CONSTRAINT FK_F77AC06B6C066AFE FOREIGN KEY (target_user_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE article_comments ADD CONSTRAINT FK_A7662417294869C FOREIGN KEY (article_id) REFERENCES articles (id)');
        $this->addSql('ALTER TABLE articles ADD CONSTRAINT FK_BFDD31681844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE articles ADD CONSTRAINT FK_BFDD316812469DE2 FOREIGN KEY (category_id) REFERENCES article_categories (id)');
        $this->addSql('ALTER TABLE articles ADD CONSTRAINT FK_BFDD3168BAD26311 FOREIGN KEY (tag_id) REFERENCES article_tags (id)');
        $this->addSql('ALTER TABLE banlist ADD CONSTRAINT FK_163B0651844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE banlist ADD CONSTRAINT FK_163B065CE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE best_streaks ADD CONSTRAINT FK_66C141A8CE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE best_streaks ADD CONSTRAINT FK_66C141A81844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE chat_messages ADD CONSTRAINT FK_EF20C9A6F624B39D FOREIGN KEY (sender_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE chat_messages ADD CONSTRAINT FK_EF20C9A61844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE current_kills ADD CONSTRAINT FK_8B7948A51844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE current_kills ADD CONSTRAINT FK_8B7948A52B284D0C FOREIGN KEY (mission_registry_id) REFERENCES mission_registries (id)');
        $this->addSql('ALTER TABLE current_kills ADD CONSTRAINT FK_8B7948A515ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE current_kills ADD CONSTRAINT FK_8B7948A5F8BD700D FOREIGN KEY (unit_id) REFERENCES units (id)');
        $this->addSql('ALTER TABLE current_kills ADD CONSTRAINT FK_8B7948A5CE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE current_kills ADD CONSTRAINT FK_8B7948A5F53666A8 FOREIGN KEY (plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE current_kills ADD CONSTRAINT FK_8B7948A544972A0E FOREIGN KEY (victim_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE current_kills ADD CONSTRAINT FK_8B7948A577F461D0 FOREIGN KEY (victim_plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE dogfights ADD CONSTRAINT FK_88B93457CE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE dogfights ADD CONSTRAINT FK_88B934571844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE dogfights ADD CONSTRAINT FK_88B934572B284D0C FOREIGN KEY (mission_registry_id) REFERENCES mission_registries (id)');
        $this->addSql('ALTER TABLE dogfights ADD CONSTRAINT FK_88B9345715ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE dogfights ADD CONSTRAINT FK_88B934579E9B4BC7 FOREIGN KEY (pilot_plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE dogfights ADD CONSTRAINT FK_88B9345744972A0E FOREIGN KEY (victim_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE dogfights ADD CONSTRAINT FK_88B9345777F461D0 FOREIGN KEY (victim_plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE dogfights ADD CONSTRAINT FK_88B93457BD5E0D4B FOREIGN KEY (ai_id) REFERENCES units (id)');
        $this->addSql('ALTER TABLE elos ADD CONSTRAINT FK_4718BD87CE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE elos ADD CONSTRAINT FK_4718BD8715ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE elos ADD CONSTRAINT FK_4718BD871844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE elos ADD CONSTRAINT FK_4718BD87F53666A8 FOREIGN KEY (plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574ACE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574A1844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574A2B284D0C FOREIGN KEY (mission_registry_id) REFERENCES mission_registries (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574A15ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574AF53666A8 FOREIGN KEY (plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE faqs ADD CONSTRAINT FK_8934BEE51844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE favor_planes ADD CONSTRAINT FK_2930ACC3CE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE favor_planes ADD CONSTRAINT FK_2930ACC31844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE favor_planes ADD CONSTRAINT FK_2930ACC3F53666A8 FOREIGN KEY (plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE featured_videos ADD CONSTRAINT FK_392957931844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE flights ADD CONSTRAINT FK_FC74B5EA1844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE flights ADD CONSTRAINT FK_FC74B5EAC80060CD FOREIGN KEY (theatre_id) REFERENCES theatres (id)');
        $this->addSql('ALTER TABLE flights ADD CONSTRAINT FK_FC74B5EA2B284D0C FOREIGN KEY (mission_registry_id) REFERENCES mission_registries (id)');
        $this->addSql('ALTER TABLE flights ADD CONSTRAINT FK_FC74B5EACE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE flights ADD CONSTRAINT FK_FC74B5EAF53666A8 FOREIGN KEY (plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE flights ADD CONSTRAINT FK_FC74B5EA15ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE flights ADD CONSTRAINT FK_FC74B5EA286FE424 FOREIGN KEY (airfield_id) REFERENCES airfields (id)');
        $this->addSql('ALTER TABLE json_messages ADD CONSTRAINT FK_77C5B09B1844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE kills ADD CONSTRAINT FK_2F673FA1CE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE kills ADD CONSTRAINT FK_2F673FA11844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE kills ADD CONSTRAINT FK_2F673FA12B284D0C FOREIGN KEY (mission_registry_id) REFERENCES mission_registries (id)');
        $this->addSql('ALTER TABLE kills ADD CONSTRAINT FK_2F673FA115ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE kills ADD CONSTRAINT FK_2F673FA1F53666A8 FOREIGN KEY (plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE kills ADD CONSTRAINT FK_2F673FA1F8BD700D FOREIGN KEY (unit_id) REFERENCES units (id)');
        $this->addSql('ALTER TABLE logs ADD CONSTRAINT FK_F08FC65C15ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE logs ADD CONSTRAINT FK_F08FC65C1844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE manuals ADD CONSTRAINT FK_8717121CF53666A8 FOREIGN KEY (plane_id) REFERENCES planes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE map_units ADD CONSTRAINT FK_69463B251844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE mission_registries ADD CONSTRAINT FK_57906A8BC80060CD FOREIGN KEY (theatre_id) REFERENCES theatres (id)');
        $this->addSql('ALTER TABLE mission_registries ADD CONSTRAINT FK_57906A8B1844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mission_registries ADD CONSTRAINT FK_57906A8B15ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE mission_registries ADD CONSTRAINT FK_57906A8BBE6CAE90 FOREIGN KEY (mission_id) REFERENCES missions (id)');
        $this->addSql('ALTER TABLE missions ADD CONSTRAINT FK_34F1D47E1844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE missions ADD CONSTRAINT FK_34F1D47EC80060CD FOREIGN KEY (theatre_id) REFERENCES theatres (id)');
        $this->addSql('ALTER TABLE online ADD CONSTRAINT FK_9E32BEEA1844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE online ADD CONSTRAINT FK_9E32BEEACE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE online ADD CONSTRAINT FK_9E32BEEAF53666A8 FOREIGN KEY (plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE pilots ADD CONSTRAINT FK_9EE6E18CA5FBE00B FOREIGN KEY (favourite_plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE pilot_game_devices ADD CONSTRAINT FK_16DC7927CE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE pilot_game_devices ADD CONSTRAINT FK_16DC7927460206D6 FOREIGN KEY (game_device_id) REFERENCES game_devices (id)');
        $this->addSql('ALTER TABLE planes ADD CONSTRAINT FK_F677FF0640F7E601 FOREIGN KEY (weather_limit_id) REFERENCES weather_limits (id)');
        $this->addSql('ALTER TABLE registration_tickets ADD CONSTRAINT FK_1437C852CE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE sender_config ADD CONSTRAINT FK_2A4111631844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE servers ADD CONSTRAINT FK_4F8AF5F7BE6CAE90 FOREIGN KEY (mission_id) REFERENCES missions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE servers ADD CONSTRAINT FK_4F8AF5F73A51721D FOREIGN KEY (instance_id) REFERENCES instances (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE server_admins ADD CONSTRAINT FK_DB9C2CC91844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE server_admins ADD CONSTRAINT FK_DB9C2CC9642B8210 FOREIGN KEY (admin_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE sorties ADD CONSTRAINT FK_488163E8CE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE sorties ADD CONSTRAINT FK_488163E81844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE sorties ADD CONSTRAINT FK_488163E8C80060CD FOREIGN KEY (theatre_id) REFERENCES theatres (id)');
        $this->addSql('ALTER TABLE sorties ADD CONSTRAINT FK_488163E82B284D0C FOREIGN KEY (mission_registry_id) REFERENCES mission_registries (id)');
        $this->addSql('ALTER TABLE sorties ADD CONSTRAINT FK_488163E815ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE sorties ADD CONSTRAINT FK_488163E8F53666A8 FOREIGN KEY (plane_id) REFERENCES planes (id)');
        $this->addSql('ALTER TABLE sorties ADD CONSTRAINT FK_488163E87F8DF58 FOREIGN KEY (takeoff_airfield_id) REFERENCES airfields (id)');
        $this->addSql('ALTER TABLE sorties ADD CONSTRAINT FK_488163E88BE8978B FOREIGN KEY (landing_airfield_id) REFERENCES airfields (id)');
        $this->addSql('ALTER TABLE streaks ADD CONSTRAINT FK_59A5DD7CCE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
        $this->addSql('ALTER TABLE streaks ADD CONSTRAINT FK_59A5DD7C1844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE streaks ADD CONSTRAINT FK_59A5DD7C15ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE units ADD CONSTRAINT FK_E9B0744991058251 FOREIGN KEY (unit_type_id) REFERENCES unit_types (id)');
        $this->addSql('ALTER TABLE visitors ADD CONSTRAINT FK_7B74A43F1844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id)');
        $this->addSql('ALTER TABLE visitors ADD CONSTRAINT FK_7B74A43F2B284D0C FOREIGN KEY (mission_registry_id) REFERENCES mission_registries (id)');
        $this->addSql('ALTER TABLE visitors ADD CONSTRAINT FK_7B74A43F15ED8D43 FOREIGN KEY (tour_id) REFERENCES tours (id)');
        $this->addSql('ALTER TABLE visitors ADD CONSTRAINT FK_7B74A43FCE55439B FOREIGN KEY (pilot_id) REFERENCES pilots (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE flights DROP FOREIGN KEY FK_FC74B5EA286FE424');
        $this->addSql('ALTER TABLE sorties DROP FOREIGN KEY FK_488163E87F8DF58');
        $this->addSql('ALTER TABLE sorties DROP FOREIGN KEY FK_488163E88BE8978B');
        $this->addSql('ALTER TABLE articles DROP FOREIGN KEY FK_BFDD316812469DE2');
        $this->addSql('ALTER TABLE articles DROP FOREIGN KEY FK_BFDD3168BAD26311');
        $this->addSql('ALTER TABLE article_comments DROP FOREIGN KEY FK_A7662417294869C');
        $this->addSql('ALTER TABLE pilot_game_devices DROP FOREIGN KEY FK_16DC7927460206D6');
        $this->addSql('ALTER TABLE servers DROP FOREIGN KEY FK_4F8AF5F73A51721D');
        $this->addSql('ALTER TABLE current_kills DROP FOREIGN KEY FK_8B7948A52B284D0C');
        $this->addSql('ALTER TABLE dogfights DROP FOREIGN KEY FK_88B934572B284D0C');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY FK_5387574A2B284D0C');
        $this->addSql('ALTER TABLE flights DROP FOREIGN KEY FK_FC74B5EA2B284D0C');
        $this->addSql('ALTER TABLE kills DROP FOREIGN KEY FK_2F673FA12B284D0C');
        $this->addSql('ALTER TABLE sorties DROP FOREIGN KEY FK_488163E82B284D0C');
        $this->addSql('ALTER TABLE visitors DROP FOREIGN KEY FK_7B74A43F2B284D0C');
        $this->addSql('ALTER TABLE mission_registries DROP FOREIGN KEY FK_57906A8BBE6CAE90');
        $this->addSql('ALTER TABLE servers DROP FOREIGN KEY FK_4F8AF5F7BE6CAE90');
        $this->addSql('ALTER TABLE alerts DROP FOREIGN KEY FK_F77AC06B6C066AFE');
        $this->addSql('ALTER TABLE banlist DROP FOREIGN KEY FK_163B065CE55439B');
        $this->addSql('ALTER TABLE best_streaks DROP FOREIGN KEY FK_66C141A8CE55439B');
        $this->addSql('ALTER TABLE chat_messages DROP FOREIGN KEY FK_EF20C9A6F624B39D');
        $this->addSql('ALTER TABLE current_kills DROP FOREIGN KEY FK_8B7948A5CE55439B');
        $this->addSql('ALTER TABLE current_kills DROP FOREIGN KEY FK_8B7948A544972A0E');
        $this->addSql('ALTER TABLE dogfights DROP FOREIGN KEY FK_88B93457CE55439B');
        $this->addSql('ALTER TABLE dogfights DROP FOREIGN KEY FK_88B9345744972A0E');
        $this->addSql('ALTER TABLE elos DROP FOREIGN KEY FK_4718BD87CE55439B');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY FK_5387574ACE55439B');
        $this->addSql('ALTER TABLE favor_planes DROP FOREIGN KEY FK_2930ACC3CE55439B');
        $this->addSql('ALTER TABLE flights DROP FOREIGN KEY FK_FC74B5EACE55439B');
        $this->addSql('ALTER TABLE kills DROP FOREIGN KEY FK_2F673FA1CE55439B');
        $this->addSql('ALTER TABLE online DROP FOREIGN KEY FK_9E32BEEACE55439B');
        $this->addSql('ALTER TABLE pilot_game_devices DROP FOREIGN KEY FK_16DC7927CE55439B');
        $this->addSql('ALTER TABLE registration_tickets DROP FOREIGN KEY FK_1437C852CE55439B');
        $this->addSql('ALTER TABLE server_admins DROP FOREIGN KEY FK_DB9C2CC9642B8210');
        $this->addSql('ALTER TABLE sorties DROP FOREIGN KEY FK_488163E8CE55439B');
        $this->addSql('ALTER TABLE streaks DROP FOREIGN KEY FK_59A5DD7CCE55439B');
        $this->addSql('ALTER TABLE visitors DROP FOREIGN KEY FK_7B74A43FCE55439B');
        $this->addSql('ALTER TABLE current_kills DROP FOREIGN KEY FK_8B7948A5F53666A8');
        $this->addSql('ALTER TABLE current_kills DROP FOREIGN KEY FK_8B7948A577F461D0');
        $this->addSql('ALTER TABLE dogfights DROP FOREIGN KEY FK_88B934579E9B4BC7');
        $this->addSql('ALTER TABLE dogfights DROP FOREIGN KEY FK_88B9345777F461D0');
        $this->addSql('ALTER TABLE elos DROP FOREIGN KEY FK_4718BD87F53666A8');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY FK_5387574AF53666A8');
        $this->addSql('ALTER TABLE favor_planes DROP FOREIGN KEY FK_2930ACC3F53666A8');
        $this->addSql('ALTER TABLE flights DROP FOREIGN KEY FK_FC74B5EAF53666A8');
        $this->addSql('ALTER TABLE kills DROP FOREIGN KEY FK_2F673FA1F53666A8');
        $this->addSql('ALTER TABLE manuals DROP FOREIGN KEY FK_8717121CF53666A8');
        $this->addSql('ALTER TABLE online DROP FOREIGN KEY FK_9E32BEEAF53666A8');
        $this->addSql('ALTER TABLE pilots DROP FOREIGN KEY FK_9EE6E18CA5FBE00B');
        $this->addSql('ALTER TABLE sorties DROP FOREIGN KEY FK_488163E8F53666A8');
        $this->addSql('ALTER TABLE articles DROP FOREIGN KEY FK_BFDD31681844E6B7');
        $this->addSql('ALTER TABLE banlist DROP FOREIGN KEY FK_163B0651844E6B7');
        $this->addSql('ALTER TABLE best_streaks DROP FOREIGN KEY FK_66C141A81844E6B7');
        $this->addSql('ALTER TABLE chat_messages DROP FOREIGN KEY FK_EF20C9A61844E6B7');
        $this->addSql('ALTER TABLE current_kills DROP FOREIGN KEY FK_8B7948A51844E6B7');
        $this->addSql('ALTER TABLE dogfights DROP FOREIGN KEY FK_88B934571844E6B7');
        $this->addSql('ALTER TABLE elos DROP FOREIGN KEY FK_4718BD871844E6B7');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY FK_5387574A1844E6B7');
        $this->addSql('ALTER TABLE faqs DROP FOREIGN KEY FK_8934BEE51844E6B7');
        $this->addSql('ALTER TABLE favor_planes DROP FOREIGN KEY FK_2930ACC31844E6B7');
        $this->addSql('ALTER TABLE featured_videos DROP FOREIGN KEY FK_392957931844E6B7');
        $this->addSql('ALTER TABLE flights DROP FOREIGN KEY FK_FC74B5EA1844E6B7');
        $this->addSql('ALTER TABLE json_messages DROP FOREIGN KEY FK_77C5B09B1844E6B7');
        $this->addSql('ALTER TABLE kills DROP FOREIGN KEY FK_2F673FA11844E6B7');
        $this->addSql('ALTER TABLE logs DROP FOREIGN KEY FK_F08FC65C1844E6B7');
        $this->addSql('ALTER TABLE map_units DROP FOREIGN KEY FK_69463B251844E6B7');
        $this->addSql('ALTER TABLE mission_registries DROP FOREIGN KEY FK_57906A8B1844E6B7');
        $this->addSql('ALTER TABLE missions DROP FOREIGN KEY FK_34F1D47E1844E6B7');
        $this->addSql('ALTER TABLE online DROP FOREIGN KEY FK_9E32BEEA1844E6B7');
        $this->addSql('ALTER TABLE sender_config DROP FOREIGN KEY FK_2A4111631844E6B7');
        $this->addSql('ALTER TABLE server_admins DROP FOREIGN KEY FK_DB9C2CC91844E6B7');
        $this->addSql('ALTER TABLE sorties DROP FOREIGN KEY FK_488163E81844E6B7');
        $this->addSql('ALTER TABLE streaks DROP FOREIGN KEY FK_59A5DD7C1844E6B7');
        $this->addSql('ALTER TABLE visitors DROP FOREIGN KEY FK_7B74A43F1844E6B7');
        $this->addSql('ALTER TABLE flights DROP FOREIGN KEY FK_FC74B5EAC80060CD');
        $this->addSql('ALTER TABLE mission_registries DROP FOREIGN KEY FK_57906A8BC80060CD');
        $this->addSql('ALTER TABLE missions DROP FOREIGN KEY FK_34F1D47EC80060CD');
        $this->addSql('ALTER TABLE sorties DROP FOREIGN KEY FK_488163E8C80060CD');
        $this->addSql('ALTER TABLE current_kills DROP FOREIGN KEY FK_8B7948A515ED8D43');
        $this->addSql('ALTER TABLE dogfights DROP FOREIGN KEY FK_88B9345715ED8D43');
        $this->addSql('ALTER TABLE elos DROP FOREIGN KEY FK_4718BD8715ED8D43');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY FK_5387574A15ED8D43');
        $this->addSql('ALTER TABLE flights DROP FOREIGN KEY FK_FC74B5EA15ED8D43');
        $this->addSql('ALTER TABLE kills DROP FOREIGN KEY FK_2F673FA115ED8D43');
        $this->addSql('ALTER TABLE logs DROP FOREIGN KEY FK_F08FC65C15ED8D43');
        $this->addSql('ALTER TABLE mission_registries DROP FOREIGN KEY FK_57906A8B15ED8D43');
        $this->addSql('ALTER TABLE sorties DROP FOREIGN KEY FK_488163E815ED8D43');
        $this->addSql('ALTER TABLE streaks DROP FOREIGN KEY FK_59A5DD7C15ED8D43');
        $this->addSql('ALTER TABLE visitors DROP FOREIGN KEY FK_7B74A43F15ED8D43');
        $this->addSql('ALTER TABLE units DROP FOREIGN KEY FK_E9B0744991058251');
        $this->addSql('ALTER TABLE current_kills DROP FOREIGN KEY FK_8B7948A5F8BD700D');
        $this->addSql('ALTER TABLE dogfights DROP FOREIGN KEY FK_88B93457BD5E0D4B');
        $this->addSql('ALTER TABLE kills DROP FOREIGN KEY FK_2F673FA1F8BD700D');
        $this->addSql('ALTER TABLE planes DROP FOREIGN KEY FK_F677FF0640F7E601');
        $this->addSql('DROP TABLE airfields');
        $this->addSql('DROP TABLE alerts');
        $this->addSql('DROP TABLE article_categories');
        $this->addSql('DROP TABLE article_comments');
        $this->addSql('DROP TABLE article_tags');
        $this->addSql('DROP TABLE articles');
        $this->addSql('DROP TABLE banlist');
        $this->addSql('DROP TABLE best_streaks');
        $this->addSql('DROP TABLE chat_messages');
        $this->addSql('DROP TABLE commands_queue');
        $this->addSql('DROP TABLE current_kills');
        $this->addSql('DROP TABLE custom_page');
        $this->addSql('DROP TABLE custom_tour_requests');
        $this->addSql('DROP TABLE dogfights');
        $this->addSql('DROP TABLE elos');
        $this->addSql('DROP TABLE events');
        $this->addSql('DROP TABLE faqs');
        $this->addSql('DROP TABLE favor_planes');
        $this->addSql('DROP TABLE featured_videos');
        $this->addSql('DROP TABLE feedbacks');
        $this->addSql('DROP TABLE flights');
        $this->addSql('DROP TABLE game_devices');
        $this->addSql('DROP TABLE instances');
        $this->addSql('DROP TABLE json_messages');
        $this->addSql('DROP TABLE kills');
        $this->addSql('DROP TABLE levels');
        $this->addSql('DROP TABLE logs');
        $this->addSql('DROP TABLE manuals');
        $this->addSql('DROP TABLE map_units');
        $this->addSql('DROP TABLE mission_registries');
        $this->addSql('DROP TABLE missions');
        $this->addSql('DROP TABLE mobile_device');
        $this->addSql('DROP TABLE online');
        $this->addSql('DROP TABLE partners');
        $this->addSql('DROP TABLE pilots');
        $this->addSql('DROP TABLE pilot_game_devices');
        $this->addSql('DROP TABLE planes');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE registration_tickets');
        $this->addSql('DROP TABLE rewards');
        $this->addSql('DROP TABLE sender_config');
        $this->addSql('DROP TABLE sender_updates');
        $this->addSql('DROP TABLE servers');
        $this->addSql('DROP TABLE server_admins');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE slides');
        $this->addSql('DROP TABLE social_links');
        $this->addSql('DROP TABLE sorties');
        $this->addSql('DROP TABLE streaks');
        $this->addSql('DROP TABLE theatres');
        $this->addSql('DROP TABLE tours');
        $this->addSql('DROP TABLE unit_types');
        $this->addSql('DROP TABLE units');
        $this->addSql('DROP TABLE visitors');
        $this->addSql('DROP TABLE weather_limits');
    }
}
