<?php

namespace App\Repository;

use App\Entity\Airfield;
use Doctrine\ORM\ORMException;

/**
 * AirfieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirfieldRepository extends BaseRepository
{
    public function getAirfieldByTitle(string $title) : ?Airfield
    {
        if (empty($title)) {
            return null;
        }
        $em = $this->getEntityManager();

        /** @var Airfield $airfieldObject */
        $airfield = $em->getRepository(Airfield::class)->findOneBy(array(
            'title' => $title,
        ));
        try {
            if (empty($airfield)) {
                $airfield = new Airfield();
                $airfield->setTitle($title);
                $em->persist($airfield);
                $em->flush();
            }
            return $airfield;
        }catch (ORMException $e) {
            $this->log("Message: {$e->getMessage()} in file: {$e->getFile()}, at line: {$e->getLine()}");
            return null;
        }
    }
}
