<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends EntityRepository
{
    const TYPE_NOTIFICATION = 'TYPE_NOTIFICATION';
    const TYPE_WARNING = 'TYPE_WARNING';
    const TYPE_NEW_TASK = 'TYPE_NEW_TASK';
    const TYPE_NEW_DOCUMENT = 'TYPE_NEW_DOCUMENT';
    const TYPE_NEW_FLIGHT = 'TYPE_NEW_FLIGHT';
    const TYPE_NEW_FLIGHT_REQUEST = 'TYPE_NEW_FLIGHT_REQUEST';
    const TYPE_FLIGHTS = 'TYPE_FLIGHTS';
    const TYPE_FLIGHT_UPDATE = 'TYPE_FLIGHT_UPDATE';
    const TYPE_DOCUMENT_ACCEPTATION = 'TYPE_DOCUMENT_ACCEPTATION';

    const CLASS_NOTIFICATION = 'fa-info-circle';
    const CLASS_WARNING = 'fa-warning';
    const CLASS_TASK = 'fa-book';
    const CLASS_DOCUMENT = 'fa-book';
    const CLASS_FIGHTER_JET = 'fa-fighter-jet';

    const MESSAGE_NEW_TASK = 'message.alert.new_task';
    const MESSAGE_NEW_DOCUMENT = 'message.alert.new_document';
    const MESSAGE_NEW_FLIGHT = 'message.alert.new_flight';
    const MESSAGE_NEW_STUDENT_FLIGHT = 'message.alert.new_student_flight';
    const MESSAGE_FLIGHT_REQUEST_UPDATED = 'message.alert.flight_request_updated';
    const MESSAGE_DOCUMENT_ACCEPTED = 'message.alert.document_checked';

    const COLOR_RED = 'text-danger';
    const COLOR_GREEN = 'text-primary';
    const COLOR_BLUE = 'text-info';
}
