<?php

namespace App\Repository;

/**
 * ArticleCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
