<?php

namespace App\Repository;

use App\Entity\BestStreak;
use App\Entity\Pilot;
use App\Entity\Server;
use Doctrine\ORM\EntityRepository;

/**
 * BestStreakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestStreakRepository extends EntityRepository
{
    /**
     * @param Pilot $pilot
     * @param Server $server
     * @param string $type
     * @return BestStreak
     */
    public function getStreak(Pilot $pilot, Server $server, $type = StreakRepository::TYPE_AIR) : ?BestStreak
    {
        /** @var BestStreak|null $streak */
        $streak = $this->findOneBy(array(
            'pilot' => $pilot,
            'server' => $server,
            'streakType' => $type,
        ));
        return $streak;
    }
}
