<?php

namespace App\Repository;

use App\Entity\Partner;
use Doctrine\ORM\EntityRepository;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends BaseRepository
{
    public function getPartners() : array
    {
        $em = $this->getEntityManager();
        $partners = $em->getRepository(Partner::class)->findAll();
        $resultArray = array();
        $i = 1; $j = 0;
        foreach ($partners as $partner){
            if(($i % 7) !== 0){
                $resultArray[$j][] = $partner;
            }else{
                $j++;
                $resultArray[$j][] = $partner;
            }
            $i++;
        }
        return $resultArray;
    }
}
