<?php

namespace App\Repository;

use App\Entity\Pilot;
use App\Entity\RegistrationTicket;
use Doctrine\ORM\ORMException;
use Monolog\Logger;

/**
 * RegistrationTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationTicketRepository extends BaseRepository
{
    /**
     * @param Pilot|null $pilot
     * @return bool
     * @deprecated
     */
    public function acceptTicket(?Pilot $pilot): bool
    {
        if (empty($pilot)) return false;

        /** @var RegistrationTicket $ticket */
        $ticket = $this->findOneBy([
            'pilot' => $pilot
        ]);
        if (empty($ticket)) return false;

        $ticket->setAccepted(true);
        try {
            $this->getEntityManager()->persist($ticket);
            $this->getEntityManager()->flush();
            return true;
        } catch (ORMException $e) {
            $this->log($e->getMessage(), Logger::ALERT, 'repository');
            return false;
        } catch (\Exception $e) {
            $this->log($e->getMessage(), Logger::ALERT, 'repository');
            return false;
        }
    }
}
