<?php

namespace App\Repository;

/**
 * TestQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
