<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnitTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitTypeRepository extends EntityRepository
{
    public const PLANES = 'Самолёты';
    public const HELI = 'Вертолёты';
    public const SHIPS = 'Воздушные, надводные судна';
    public const ARMORED = 'Бронетехника';
    public const ARTILLERY = 'Артиллерия';
    public const SAM = 'ПВО';
    public const UNARMED = 'Невооружённые';
    public const INFANTRY = 'Пехота';
    public const STATICS = 'Статические обьекты';
    public const UNDEFINED = 'Неопределено';
    public const FORTIFICATION = 'Вооружённые укрепления';

    public const TYPE_SHIPS = 'Ships';

    public static function getRealCategory($category): ?string
    {
        return match ($category) {
            'Plane' => self::PLANES,
            'HELI' => self::HELI,
            'Ship' => self::SHIPS,
            'Armor' => self::ARMORED,
            'Artillery' => self::ARTILLERY,
            'Air Defence' => self::SAM,
            'Unarmed' => self::UNARMED,
            'Infantry' => self::INFANTRY,
            'Static' => self::STATICS,
            'UNDEFINED' => self::UNDEFINED,
            'Fortification' => self::FORTIFICATION,
            default => null,
        };
    }
}
